version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - my-datavolume:/var/lib/mysql
      - "./scripts/create-databases.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/create-db-hr.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./scripts/create-db-inventory.sql:/docker-entrypoint-initdb.d/3.sql"
      - "./scripts/create-db-invoicing.sql:/docker-entrypoint-initdb.d/4.sql"
      - "./scripts/create-db-store.sql:/docker-entrypoint-initdb.d/5.sql"
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  my-datavolume: